### ISSUE TITLE
Bundle should not be deleted while it owns some resources

### ISSUE THREAD

**Issue by ash2k** [atlassian/smith#225]
Need to verify that owner references with "block owner deletion" flag actually work as expected. If not, Bundle should have a finalizer to block deletion.

**Comment by nilebox** [comment]
@ash2k comment for `BlockOwnerDeletion` says the following:
```go
	// If true, AND if the owner has the "foregroundDeletion" finalizer, then
	// the owner cannot be deleted from the key-value store until this
	// reference is removed.
	// Defaults to false.
	// To set this field, a user needs "delete" permission of the owner,
	// otherwise 422 (Unprocessable Entity) will be returned.
	// +optional
	BlockOwnerDeletion *bool `json:"blockOwnerDeletion,omitempty" protobuf:"varint,7,opt,name=blockOwnerDeletion"`
```
i.e. Bundle needs to have a "foregroundDeletion" finalizer.
See https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion
> The object’s metadata.finalizers contains the value “foregroundDeletion”.

In other words, we need to manually add a "foregroundDeletion" to the list of Bundle finalizers. And after that the Garbage Collector should delete all the objects respecting the dependency graph.

**Comment by nilebox** [comment]
In order to make GC work for deletion of resources, we should also set an `ownerReference` to the owner Bundle, but currently we only add a label:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  creationTimestamp: 2018-02-13T04:21:35Z
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  labels:
    smith.atlassian.com/BundleName: v-test
  name: showenv--sqs
  namespace: sctest
  ownerReferences:
  - apiVersion: servicecatalog.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: ServiceInstance
    name: sqs
    uid: 584cc40a-1075-11e8-8819-32d7bcc7b2c9
  resourceVersion: "1302"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/sctest/servicebindings/showenv--sqs
  uid: 60a01f18-1075-11e8-8819-32d7bcc7b2c9
```

**Comment by nilebox** [comment]
I'll pick up this task and try to fix it using `foregroundDeletion`.

**Comment by nilebox** [comment]
I made an experiment to check the behavior of deletion with `blockOwnerDeletion`.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: root
  namespace: sctest
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: middle
  namespace: sctest
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Secret
    name: root
    # replace UID with the actual one after create and update it
    uid: 8c9ed2c3-109c-11e8-ba18-0a517c7aa8f4
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: leaf
  namespace: sctest
  finalizers: # should block deletion of parent?
  - nislamov/test-blocker
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Secret
    name: middle
    # replace UID with the actual one after create and update it
    uid: 8cba4a7a-109c-11e8-ba18-0a517c7aa8f4
type: Opaque
```
- created 3 secrets (`root`, `middle` and `leaf`)
- marked them with ownerReferences (`root` <- `middle` <- `leaf`) with `blockOwnerDeletion: true`
- marked the `leaf` secret with `nislamov/test-blocker` finalizer (which should prevent this object from deletion)
- deleted the `root` resource:
```
❯ k delete secret -n sctest root
secret "root" deleted
```
Result: `root` and `middle` secrets are gone, `leaf` secret is marked with `deletionTimestamp`, but still exists (because of custom finalizer).
