### ISSUE TITLE
Add support for referencing bundle from resources

### ISSUE THREAD

**Issue by nilebox** [atlassian/smith#82]
Use case: generate resource names based on the bundle name (see `name: {{#metadata.name}}-sleeper1` for example):
```yaml
apiVersion: smith.atlassian.com/v1
kind: Bundle
metadata:
  name: bundlex
spec:
  resources:
  - name: sleeper1
    spec:
      apiVersion: tpr.atlassian.com/v1
      kind: Sleeper
      metadata:
        name: {{#metadata.name}}-sleeper1
      spec:
        sleepFor: 3
        wakeupMessage: Hello 1 from bundle {{#metadata.name}}!
  - name: sleeper2
    dependsOn:
    - sleeper1
    spec:
      apiVersion: tpr.atlassian.com/v1
      kind: Sleeper
      metadata:
        name: {{#metadata.name}}-sleeper1
      spec:
        sleepFor: 4
        wakeupMessage: "{{sleeper1.status.message}}"
  - name: sleeper3
    dependsOn:
    - sleeper2
    spec:
      apiVersion: tpr.atlassian.com/v1
      kind: Sleeper
      metadata:
        name: sleeper3
      spec: "{{{sleeper2.spec}}}"
```

Some "global variables" defined within bundle would also work.
